### ISSUE TITLE
Detailed exam report

### ISSUE THREAD

**Issue by ielizaga** [ielizaga/gpcheckintegrity#10]
This issue has been raised to track the development of "generate a final report" functionality. Right now, the program exits without generating a final report other than the command line output.

**Comment by Zerpet** [comment]
I'm thinking of implementing this using a list to gather the tables with errors, and print all the tables at the end with proper report format. Maybe write the report to a file?

In any case, going with the shared object solution, I'll need to play with locks.

Did you have any different idea @ielizaga ?
