### ISSUE TITLE
Refactor optparse to argparse

### ISSUE THREAD

**Issue by Zerpet** [ielizaga/gpcheckintegrity#18]
The module `optparse` is [deprecated](https://docs.python.org/2/library/optparse.html). We should move on from this module and use [argparse](https://docs.python.org/2/library/argparse.html#module-argparse).

This could be a good opportunity to move a bit away from `gppylib` if there is not much complexity involved.

**Comment by ielizaga** [comment]
argparse is not available in 2.6.

**Comment by Zerpet** [comment]
Refactoring using `optparse` instead

**Comment by Zerpet** [comment]
Should I try to user the options from parser is not given as argument in `def connect()` ?

https://github.com/ielizaga/gpcheckintegrity/blob/master/gpcheckintegrity#L118-L131

**Comment by ielizaga** [comment]
Closed in #39
