### ISSUE TITLE
Refactor the help page

### ISSUE THREAD

**Issue by Zerpet** [ielizaga/gpcheckintegrity#31]
The current help function is a massive string inside a print. This is rather ugly and we should use something more elegant. `ArgParse` provides some sort of mechanism to build the help page.

In this issue, we should explore possibilities and move away from "the massive string" solution.

At the moment, this is blocked by #18

**Comment by Zerpet** [comment]
I think this one is blocked by #18

**Comment by Zerpet** [comment]
This one will actually come in the PR resulted from issue #18

**Comment by ielizaga** [comment]
Closed in #39
