### ISSUE TITLE
Check integrity of tables within a specific schema

### ISSUE THREAD

**Issue by Zerpet** [ielizaga/gpcheckintegrity#4]
This issue is to track the development of the feature "integrity of tables within a single schema". Right now, the tool checks all the tables in all the schemas in the DB. After this enhancement, the tool will accept a command line option to check the tables in a specific schema.

**Comment by ielizaga** [comment]
Assigning to @ielizaga for verification.

**Comment by ielizaga** [comment]
Verified. Pull request #6 merged into master.
