### ISSUE TITLE
Check integrity of tables for all databases

### ISSUE THREAD

**Issue by ielizaga** [ielizaga/gpcheckintegrity#7]
This issue is to track the development of the feature "integrity of tables within multiple databases". Right now, the tool checks all the tables in one specific DB. After this enhancement, the tool will accept a command line option to check the tables in all databases found in Greenplum.

**Comment by Zerpet** [comment]
As we discussed offline today, makes more sense to add an option to check all the databases. An option to check arbitrary DBs will not make much sense as `gpcheckintegrity` can be used within a script and run once per DB.

**Comment by ielizaga** [comment]
Resolved in 37a2e5547f28ef0252f554e5ac7c43962dcb1a6b.
